name = "CYTools"
uuid = "6ac8560f-9240-4675-9403-0b04e120aa3e"
authors = ["Martin Bies <MBies87@googlemail.com> and Andres Rios Tascon <andres@mail.ariostas.com>"]
version = "0.1.0"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Oscar = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
